
from bot.locals import Local

LOCAL = Local({
    'WRONG_ROOM' : 'Eu não deveria estar aqui..\nID : <code>{CHAT_ID}</code>',
    'WELCOME_MESSAGE' : "Ola! Digite /help.",
    'PASS_REQUIRED' : '\n\nDigite <code>/{cmd_pass} </code>Com sua senha',
    'LEECH_LIST_MESSAGE_HEADER' : '<b>Status de Download/Upload</b>',
    'LEECH_LIST_FORMAT' : 'Nome: <code>{name}</code>\nStatus: {status}\nID: <code>{gid}</code>\n\n',
    'ARIA2_CHECKING_LINK' : "Verificando...",
    'ARIA2_DOWNLOAD_STATUS' : "Downloading : <code>{name}</code>\n{block} {percentage}\nTamanho : {total_size}\nDN : {download_speed} / UP : {upload_speed}\nSeeder : {seeder}\nETA : {eta}\nID : <code>{gid}</code>",
    'ARIA2_DOWNLOAD_SUCCESS' : 'Arquivo baixado : <code>{name}</code>',
    'ARIA2_DOWNLOAD_CANCELED' : 'Download cancelado : <code>{name}</code>',
    'ARIA2_DEAD_LINK' : 'Download cancelado automaticamente : <code>{name}</code>\nSeu link esta morto.',
    'ARIA2_NO_URI' : 'Link invalido.',
    'UPLOADING_FILE' : 'Uploading : <code>{name}</code>',
    'UPLOADING_PROGRESS' : 'Uploading : <code>{name}</code>\n{block} {percentage}%\nTamanho : {size}\nUP : {upload_speed}/s\nETA : {eta}',
    'UPLOAD_FAILED_FILE_MISSING' : 'Upload : Fracassado. arquivo não encontrado.\n<code>{name}</code>',
    'GENERATE_THUMBNAIL' : 'Thumbnail : Gerando.\n<code>{name}</code>',
    'SPLIT_FILE' : 'Dividir : <code>{name}</code>',
    'SPLIT_FAILED' : 'Dividir : Falhou.\n<code>{name}</code>',
    'THUMBNAIL_NO_PHOTO' : 'Digite o comando <code>/{cmd_set_thumbnail}</code> na legenda da foto.',
    'THUMBNAIL_DOWNLOADING' : 'Downloading thumbnail.',
    'THUMBNAIL_DOWNLOADED' : 'Thumbnail download.',
    'THUMBNAIL_APPLIED' : 'Thumbnail aplicada.',
    'THUMBNAIL_DELETING' : 'Thumbnail deletada.',
    'THUMBNAIL_RESET' : 'Thumbnail resetada.',
    'UPLOAD_AS_DOC' : 'Mudar arquivo para documento {status}.',
    'UPLOAD_AS_ZIP' : 'Mudar arquivo para ZIP {status}.',
    'TRACKER_RESET' : 'Default torrent tracker reset.',
    'TRACKER_APPLIED' : 'Default torrent tracker applied.',
    'HELP_MESSAGE_HEADER' : '<b>Comandos do Bot</b>',
    'NO_HELP_INFO' : 'Sem informação',
    'COMMAND_START' : 'start bot',
    'COMMAND_PASSWORD' : 'Digitar senha',
    'COMMAND_HELP' : 'Esta mensagem',
    'COMMAND_LEECH' : 'leech link or magnet',
    'COMMAND_CANCEL_LEECH' : 'cancel leeching',
    'COMMAND_LEECH_LIST' : 'list on going leech',
    'COMMAND_SET_THUMBNAIL' : 'set custom video thumbail',
    'COMMAND_RESET_THUMBNAIL' : 'reset custom video thumbnail',
    'COMMAND_UPLOAD_AS_DOC' : 'toggle upload anything as document',
    'COMMAND_UPLOAD_AS_ZIP' : 'toggle upload anything as bundled zipfile',
    'COMMAND_SET_TRACKER' : 'set default tracker, sparated by newline',
    'BLOCK_EMPTY' : "▱",
    "BLOCK_FILLED" : "▰"
})
